version: "3.8"

services:
    traefik:
        image: traefik:2.11
        container_name: traefik
        restart: unless-stopped
        networks:
            - traefik_proxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        command:
            - --api=true
            - --api.dashboard=true
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.websecure.http.tls.options=default
            - --entrypoints.websecure.http.tls.domains[0].main=${DOMAINNAME}
            - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAINNAME}
            # - --entrypoints.websecure.forwardedHeaders.trustedIPs=${LOCAL_IPS},173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
            - --providers.docker=true
            - --providers.docker.endpoint=unix:///var/run/docker.sock
            - --providers.docker.network=traefik_proxy
            - --providers.docker.exposedByDefault=false
            - --providers.docker.swarmMode=false
            - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
            - --certificatesresolvers.letsencrypt.acme.tlsChallenge=true
            - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.tls.certresolver=letsencrypt
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.middlewares=auth,securityheaders
            - traefik.http.middlewares.auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}
            - traefik.http.middlewares.securityheaders.headers.forceSTSHeader=true
            - traefik.http.middlewares.securityheaders.headers.stsPreload=true
            - traefik.http.middlewares.securityheaders.headers.stsSeconds=315360000
            - traefik.http.middlewares.securityheaders.headers.stsIncludeSubdomains=true
        volumes:
            - $DOCKERDIR/logs/traefik:/logs
            - $DOCKERDIR/services/traefik/rules:/rules
            - $DOCKERDIR/services/traefik/acme:/etc/traefik/acme
            - /var/run/docker.sock:/var/run/docker.sock:ro

    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        restart: unless-stopped
        networks:
            - traefik_proxy
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - $DOCKERDIR/services/homepage:/app/config
            - $DOCKERDIR/logs/homepage:/app/config/logs
        labels:
            - traefik.enable=true
            - traefik.http.routers.homepage.rule=Host(`$DOMAINNAME`)
            - traefik.http.routers.homepage.entrypoints=websecure
            - traefik.http.routers.homepage.tls.certresolver=letsencrypt
            - traefik.http.routers.homepage.middlewares=auth,securityheaders
            - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
    traefik_proxy:
        name: traefik_proxy
        external: true
